import {
  Home,
  Perfil,
  Settings,
  Employees,
  Restaurants,
  Dishes,
  Reservations,
} from 'screens'

export const privateRoutes = [
  {
    key: 1,
    path: `/`,
    title: `Inicio`,
    icon: `home`,
    component: Home,
    permission: [``],
  },
  {
    key: 2,
    path: `/employees`,
    title: `Trabajadores`,
    icon: `person`,
    component: Employees,
    permission: [``],
  },
  {
    key: 3,
    path: `/dishes`,
    title: `Platos`,
    icon: `local`,
    component: Dishes,
    permission: [``],
  },
  {
    key: 4,
    path: `/restaurants`,
    title: `Sucursal`,
    icon: `store`,
    component: Restaurants,
    permission: [``],
  },
  {
    key: 5,
    path: `/reservations`,
    title: `Reservación`,
    icon: `event`,
    component: Reservations,
    permission: [``],
  },
  {
    key: 6,
    path: `/perfil`,
    title: `Perfil`,
    icon: `account`,
    component: Perfil,
    permission: [``],
    hide: true,
  },
  {
    key: 7,
    path: `/setting`,
    title: `Configuración`,
    icon: `settings`,
    component: Settings,
    permission: [``],
    hide: true,
  },
]
